name: Release Binaries

on:
  release:
    types:
    - created
    - published
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v1.4.5). Can ignore this if selecting workflow run from a release tag.'
        required: false
        type: string
        default: ''

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.tag_name || github.ref_name }}
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: cmd/envsubst
        asset_name: envsubst-Linux-x86_64
        compress_assets: OFF
        release_name: ${{ inputs.tag_name || '' }}
  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.tag_name || github.ref_name }}
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm64
        project_path: cmd/envsubst
        asset_name: envsubst-Linux-arm64
        compress_assets: OFF
        release_name: ${{ inputs.tag_name || '' }}
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.tag_name || github.ref_name }}
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        project_path: cmd/envsubst
        asset_name: envsubst-Darwin-x86_64
        compress_assets: OFF
        release_name: ${{ inputs.tag_name || '' }}
  release-darwin-arm64:
    name: release darwin/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.tag_name || github.ref_name }}
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: arm64
        project_path: cmd/envsubst
        asset_name: envsubst-Darwin-arm64
        compress_assets: OFF
        release_name: ${{ inputs.tag_name || '' }}
  release-windows:
    name: release windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.tag_name || github.ref_name }}
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        project_path: cmd/envsubst
        binary_name: envsubst-windows #release fails if the binary name is the same as the asset name
        asset_name: envsubst
        compress_assets: OFF
        release_name: ${{ inputs.tag_name || '' }}
