name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v1.4.5)'
        required: true
        type: string
      release_title:
        description: 'Release title (optional)'
        required: false
        type: string
        default: ''
      release_body:
        description: 'Release description (optional)'
        required: false
        type: string
        default: ''

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check if tag already exists
        if git rev-parse "${{ inputs.tag_name }}" >/dev/null 2>&1; then
          echo "Tag ${{ inputs.tag_name }} already exists, skipping tag creation"
        else
          git tag -a "${{ inputs.tag_name }}" -m "Release ${{ inputs.tag_name }}"
          git push origin "${{ inputs.tag_name }}"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: ${{ inputs.release_title || inputs.tag_name }}
        body: ${{ inputs.release_body }}
        draft: false
        prerelease: false
      continue-on-error: true

    - name: Release binaries
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'binaries.yml',
            ref: '${{ inputs.tag_name }}',
            inputs: {
              tag_name: '${{ inputs.tag_name }}'
            }
          });
